---
title: "MPDW Praktikum Pertemuan 2"
author: "Nizar Hermawan (G1401231054)"
date: "2025-09-02"
output: html_document
---

```{r}
library(lmtest) # Untuk Uji Durbin-Watson
library(orcutt) # Untuk metode Cochrane-Orcutt
library(HoRM)   # Untuk metode Hildreth-Lu

#baca data "C:\Users\Nizar\Downloads\Documents\bps-od_15042_indeks_pmbngnn_manusia__prov_di_indonesia_data.csv"
library(readr)
dt_ipm <- read_csv("C:/Users/Nizar/Downloads/Documents/bps-od_15042_indeks_pmbngnn_manusia__prov_di_indonesia_data.csv")

# Lihat datanya
print(dt_ipm)
```

```{r}
model_awal <- lm(IPM ~ Tahun, data = dt_ipm)
summary(model_awal)
```
```{r}
# Ambil sisaan dari model
sisaan_awal <- residuals(model_awal)

# Plot sisaan terhadap waktu
plot(dt_ipm$Tahun, sisaan_awal, type="o", pch=20, col="red",
     main="Plot Sisaan vs Waktu", xlab="Tahun", ylab="Sisaan")
abline(h=0, lty=2) # Gar
```
```{r}
dwtest(model_awal)
```
```{r}
model_co <- cochrane.orcutt(model_awal)
summary(model_co)

# rho paling optimum
rho <- model_co$rho
cat("Rho optimum:", rho)
```
```{r}
ipm.trans <- dt_ipm$IPM[-1] - dt_ipm$IPM[-12]*rho

tahun.trans <- dt_ipm$Tahun[-1] - dt_ipm$Tahun[-12]*rho
model_co_manual <- lm(ipm.trans~tahun.trans)

b0_co_manual <- coef(model_co_manual)[1]/(1-rho)
b1_co_manual <- coef(model_co_manual)[2]
cat("Koefisien manual Cochrane-Orcutt:\n")
cat("b0:", b0_co_manual, "\n")
cat("b1:", b1_co_manual, "\n")
```
```{r}
hildreth.lu.func<- function(r, model){
  x <- model.matrix(model)[,-1]
  y <- model.response(model.frame(model))
  n <- length(y)
  t <- 2:n
  y <- y[t]-r*y[t-1]
  x <- x[t]-r*x[t-1]
  
  return(lm(y~x))
}

#Pencariab rho yang meminimumkan SSE
r <- c(seq(0.1,0.9, by= 0.1))
tab <- data.frame("rho" = r, "SSE" = sapply(r, function(i){deviance(hildreth.lu.func(i, model_awal))}))
round(tab, 4)
```

```{r}
#Rho optimal di sekitar 0.4
rOpt <- seq(0.6,0.9, by= 0.001)
tabOpt <- data.frame("rho" = rOpt, "SSE" = sapply(rOpt, function(i){deviance(hildreth.lu.func(i, model_awal))}))
head(tabOpt[order(tabOpt$SSE),])
```

```{r}
#Grafik SSE optimum
par(mfrow = c(1,1))
plot(tab$SSE ~ tab$rho , type = "l", xlab = "Rho", ylab = "SSE")
abline(v = tabOpt[tabOpt$SSE==min(tabOpt$SSE),"rho"], lty = 2, col="red",lwd=2)
text(x=0.736	, y=3.652700	, labels = "rho=0.736	", cex = 0.8)
```
```{r}
modelHL <- hildreth.lu(dt_ipm$IPM, dt_ipm$Tahun, rho = 0.736)
summary(modelHL)
```
```{r}
#Transformasi Balik
cat("y = ", coef(modelHL)[1]/(1-0.736), "+", coef(modelHL)[2],"x", sep = "")
```

```{r}
#Deteksi autokorelasi
dwtest(modelHL)
```

```{r}
# Menghitung SSE untuk setiap model secara manual
sse_awal <- sum(residuals(model_awal)^2)
sse_co <- sum(residuals(model_co)^2)
sse_hl <- sum(residuals(modelHL)^2)

# Membuat tabel perbandingan
data.frame(
  Metode = c("Model Awal (Sakit)", "Cochrane-Orcutt (Sehat)", "Hildreth-Lu (Sehat)"),
  SSE = c(sse_awal, sse_co, sse_hl),
  DW_Statistic = c(dwtest(model_awal)$statistic, model_co$DW[3], dwtest(modelHL)$statistic)
)

```

# Kesimpulan
Pada penanganan autokorelasi pada IPM Nasional pada tahun 2010-2024,  metode Hildreth-Lu menghasilkan model baik dengan model SSE terkecil (3.6527) dan nilai statistik Durbin-Watson (2.0426) yang menunjukkan tidak adanya autokorelasi. Metode Cochrane-Orcutt juga efektif dengan SSE sebesar 3.6527000 dan DW sebesar 2.1624021.